nixos/gnome: Fix eval for gnome-flashback
error: Default graphical session, 'gnome-flashback-metacity', not found.

Fixes f192bd9e5cc9bd42783c1b5e7f8b8538c1285cd6.

(cherry picked from commit 32eeaa50134aa425fe7fcf24041cd2801be40753)